name: Testing the bot in this repo
on:
  issue_comment:
    types:
      - created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types:
      - created
  push:

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: georgepstaylor/telegram-notify
      with:
        telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        gh_event: ${{ github.event_name }}
        gh_actor: ${{ github.actor }}